### ISSUE TITLE
Let's rename project to something like intellij-memory-toolbox-plugin

### ISSUE THREAD

**Issue by xnike** [Salomon88/intellij-performance-toolbox-plugin#17]
As we want our plugin to support more features than just gcViewer wrapper, let's find a more appropriate plugin name, something like [intellij-csv-validator](https://github.com/SeeSharpSoft/intellij-csv-validator)

**Comment by xnike** [comment]
Plus it'll be better discoverable via search engines)

**Comment by xnike** [comment]
Or maybe even `intellij-performance-toolbox-plugin` as GC and memory leaks could affect overall performance.

**Comment by Salomon88** [comment]
Renamed
