### ISSUE TITLE
[GC] Filter missing "Young Generation"

### ISSUE THREAD

**Issue by OliverO2** [Salomon88/intellij-performance-toolbox-plugin#40]
Plugin version: 1.0.2

GCViewer 1.36 provides a view toggle for "Young Generation" (right below "Tenured Generation"). This option is missing in the plugin's filter toggles.

**Comment by Salomon88** [comment]
Please update plugin

**Comment by OliverO2** [comment]
Tested the update, works as expected. Thanks!
